# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'LocusSDKFramework', :git => 'git@github.com:locus-taxy/LocusSDKFramework.git' , :branch => 'ES-24031-SampleAppWithFramework'

  # Pods for SampleApp

  target 'SampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
